### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by gaou-piou** [darionco/rollup-plugin-web-worker-loader#4] opened 2019-09-21 08:38 UTC
i import it like this
`import ProfileWorker from 'web-worker:./profile_worker.js'`

and returns

`(plugin web-worker-loader) TypeError: Could not load /Volumes/TIMELESS/tmp/app/src/views/Conversation/services/profile_worker.js (imported by src/views/Conversation/services/profile.js): The "path" argument must be of type string. Received type undefined`

**Comment by darionco** [comment] 2019-09-27 13:17
Could you give me more information about your environment and your rollup configuration?
I am having trouble reproducing the bug. Please include:

- Node version
- Rollup version
- Rollup configuration

Thanks

**Comment by gaou-piou** [comment] 2019-10-02 23:45
node version: v12.10.0
npm version: 6.9.0
rollup version: 1.22.0

I use it with svelte. Maybe this is the problem?

**Comment by darionco** [comment] 2019-10-03 23:43
Maybe... could you put together a minimum project that shows the problem?
If you can't do it, I'll try to do it myself in a couple days.

**Comment by MegazeroMZ** [comment] 2019-11-15 19:10
Im seeing something pretty similar to this one. My error look like this:

(plugin web-worker-loader) TypeError [ERR_INVALID_ARG_TYPE]: Could not load /home/USER/PROJECT/src/worker.js (imported by /home/USER/PROJECT/src/main.js): The "path" argument must be of type string. Received type undefined

After a while I found out that if I have rollup-plugin-flow-entry plugin used in my rollup config (it doesnt matter if I put it before or after this plugin) then I that error happen, not sure why yet, especially when the main.js and worker.js file are both not flow-enabled.

**Comment by mAKEkr** [comment] 2019-11-28 16:22
I had the same problem using the svelte template, and I changed the format in the `rollup.config.js` file to `esm` and solved it.

**Comment by darionco** [comment] 2019-11-30 05:54
While fixing a different bug I ran into this error, a fix was published in version 0.8.0, I am not sure that it fixes all of the errors that have been reported here though. If you guys could test on your projects, that would be awesome.

Thanks!

**Comment by MegazeroMZ** [comment] 2019-12-02 21:23
So Im trying to dig into the code to see what's wrong, and it seem like somehow the rollup option (which should contain output { dir: "/dist", format: "es" etc }) is modified somewhere in this plugin?) And when it come to the next package that using rollup option (in my case rollup-flow-entry plugin which have a generateBundle(option, bundle) hook and) the option is missing the output dir, which then give out that error we see here.

**Comment by darionco** [comment] 2019-12-02 23:18
interesting, that would indeed be a problem, the way the plugin works is by taking the original configuration and running a separate instance of rollup using the worker code as the entry point. Once the new instance finishes it encodes the resulting bundle and returns it as the worker file.

Seems to me that there's an incompatibility between the way this plugin processes the files and other plugins that modify the package in the `generateBundle` step...

Is there a way you could share your code with me so I can take a look and hopefully fix this issue?

Thanks!

**Comment by GerardRodes** [comment] 2020-02-27 12:46
You should prefix your virtual module helper `rollup-plugin-web-worker-loader::helper` with `\0` as rollup conventions dictates
> If your plugin uses 'virtual modules' (e.g. for helper functions), prefix the module ID with \0. This prevents other plugins from trying to process it.

https://rollupjs.org/guide/en/#plugin-development

**Comment by darionco** [comment] 2020-03-02 16:08
yeah, I thought about prefixing the module with `\0` but there were situations where it wouldn't work, I'll look into it again.

**Comment by darionco** [comment] 2020-04-26 23:50
Closing this issue as it seems to be a problem with specific plugins. This plugin has the ability to skip plugins during its build and all the other concerns have been fixed in version 1.0.0

**Closed as completed by darionco** 2020-04-26 23:50 UTC
