### ISSUE TITLE
 ParseError: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by btzr-io** [darionco/rollup-plugin-web-worker-loader#35] opened 2020-10-22 01:10 UTC
I keep getting this error when I try to import the web-worker.
>[0] ParseError:  rollup-plugin-worker-loader::module:\src\react-app\store\worker.js
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[0]     at validateString (internal/validators.js:117:11)
[0]     at Object.dirname (path.js:583:5)'

Is there something wrong with my config file or this module is not supported by `nollup`.

I'm trying to import it Like this:
> Path: src\react-app\store\index.js
```JS
import StoreWorker from 'web-worker:./worker';
```

The worker is in the same directory:
> Path: src\react-app\store\worker.js

Rollup config:

```JS
import path from 'path';
import alias from '@rollup/plugin-alias'
import babel from '@rollup/plugin-babel';;
import hotcss from 'rollup-plugin-hot-css';
import refresh from 'rollup-plugin-react-refresh';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import webWorkerLoader from 'rollup-plugin-web-worker-loader';
import { terser } from 'rollup-plugin-terser';

const root = path.resolve(__dirname);

let env = function () {
    return {
        banner: `
            self.process = {
                env: {
                    NODE_ENV: ${JSON.stringify(process.env.NODE_ENV)}
                }
            };
        `
    }
};

let config = {
    input: './src/react-app/main.js',
    output: {
        dir: 'dist',
        format: 'esm',
        entryFileNames: '[name].[hash].js',
        assetFileNames: '[name].[hash][extname]',
    },
    plugins: [
        env(),
        alias({
            entries: [
                { find: '@app', replacement: path.resolve(root, 'src/react-app') }
            ]
        }),
        babel({
            sourceMaps: false,
            babelHelpers: 'bundled',
            exclude: 'node_modules/**'
        }),
        hotcss({
            hot: process.env.NODE_ENV === 'development',
            filename: 'styles.css'
        }),
        resolve(),
        commonjs(),
        webWorkerLoader(),
        process.env.NODE_ENV === 'development' && refresh()
    ]
}

export default config;
```

**Comment by darionco** [comment] 2020-11-16 03:02
I am sorry for the late reply, I haven't been able to reproduce this bug, do you have a repo or an example project that I can look at?
Thank you in advance!

**Comment by darionco** [comment] 2020-11-25 19:25
Closing as I am not able to reproduce, feel free to re-open with more details, for now I would try putting this plugin before `babel`.

**Closed as completed by darionco** 2020-11-25 19:25 UTC
Labels: bug

**Comment by willmorgan** [comment] 2021-01-19 22:39
@darionco For me, this seems to be caused by the url plugin. As you mention in #4 we're free to exclude the url plugin.

However I imagine this is a familiar use case: this plugin loads Worker files, which in turn use the url plugin to import things like WASM binaries - which make sense to be loaded in by external URL since you can stream them.

To work around this in a nicer way, I think it might be possible to `postMessage` in the resources after the Worker starts but I'll have a dig around and see if we can get a repro up in any case.

**Comment by yaoshiyang** [comment] 2022-09-22 13:40
> @darionco For me, this seems to be caused by the url plugin. As you mention in #4 we're free to exclude the url plugin.
> 
> However I imagine this is a familiar use case: this plugin loads Worker files, which in turn use the url plugin to import things like WASM binaries - which make sense to be loaded in by external URL since you can stream them.
> 
> To work around this in a nicer way, I think it might be possible to `postMessage` in the resources after the Worker starts but I'll have a dig around and see if we can get a repro up in any case.
so, how to resolve in use url plugin ??

**Comment by yaoshiyang** [comment] 2022-09-22 13:42
> @darionco For me, this seems to be caused by the url plugin. As you mention in #4 we're free to exclude the url plugin.
> 
> However I imagine this is a familiar use case: this plugin loads Worker files, which in turn use the url plugin to import things like WASM binaries - which make sense to be loaded in by external URL since you can stream them.
> 
> To work around this in a nicer way, I think it might be possible to `postMessage` in the resources after the Worker starts but I'll have a dig around and see if we can get a repro up in any case.

 ## so, how to resolve in  use url plugin ??
